### ISSUE TITLE
BoardFragment

### ISSUE THREAD

**Issue by jkey20** [dahaeng/dahaeng-android#19]
- [ ] **내 일정 목록 표시**
일정 목록의 more 버튼을 누르면 공유, 수정, 삭제 가능

- [ ] **공유**
카카오톡으로 공유
메시지 하단 버튼 클릭시 TaskActivity 이동 -> TaskingFragment 표시

- [ ] **수정**
수정버튼 클릭시 TaskActivity 이동 -> ReschduleFragment 표시

- [ ] **삭제**
삭제버튼 클릭시 Firebase 에서 해당일정 삭제

- [ ] **새 일정 생성**
TaskActivity 이동 -> CreateScheduleFragment 표시

- [ ] **Fragment 로 돌아올때마다 스케줄 갱신**

**Comment by jisungbin** [comment]
## CLOSE

현재는 구상이 달라짐
