### ISSUE TITLE
고쳐야 하는 부분들 

### ISSUE THREAD

**Issue by dev210202** [dahaeng/dahaeng-android#25]
- [x] 내 일정 최초 실행시 리스트 표시 안됨
- [x] 리스트가 표시안된채로 일정 생성을 진행하고 일정들을 받아와도 리스트에 표시 안됨<br/>- ScheduleFragment에서 Lifecycle 문제로 예상됨

**Comment by jisungbin** [comment]
고쳐보겠숩니더

완료: https://github.com/dahaeng/dahaeng-android/pull/26
